name: context_example
on: 
  workflow_dispatch
env:
  name: ajin
  age: 23

jobs:
  context1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
      - run: | 
          echo " the repo name is " ${{github.repository}}
          echo " the os of the runner is " ${{runner.os}}
          echo " the architecture is " ${{runner.arch}}
          
      - name: step2
      - run: |
          echo " My name is $name and my age is $age"
