name: sample env
on:
  workflow_dispatch

env:
  name: ajin
  job: ips

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "i am $name"
          echo "i am an $job officer"

  job2:
    runs-on: ubuntu-latest
    env:
      name: Akash
      job: clapping
    steps:
      - name: step2
        run: |
          echo "my friend is $name"
          echo "his job is $job"
